### PR TITLE
feat: :sparkles: Improved tobot-math and added pre compiled headers

### PR DESCRIPTION
**Pull request by FrederikTobner**
My vector's like a line in space,
Its magnitude and direction true
It can define a plane,
Or any point of view.

It's versatile and ever-changing,
It's a tool to solve equations,
It can help us find a solution
For any problem, a game engine implementation might be introducing.

My vector's like a ray of light,
It's a tool to measure space,
It can help us find the answer
To any problem that we might face.

It's versatile and ever-changing,
It's a tool to calculate,
It can help us solve equations,
And make our life much great.

My vector's like a compass rose,
It's a tool to show the way,
It can guide us on our journey
So we can reach our destination of creating our own engine someday.

### CODE REVIEW

**Comment by FrederikTobner** [comment]
Confusion, a feeling of despair
Thoughts racing in my head, can't find a single pair
Mind in a spin, can't focus or concentrate
Too many clouds, no sign of the sun

My heart is heavy, with no end in sight
It's hard to move on, when I'm stuck in this plight
The future uncertain, no idea what it holds
No answers in sight, just a dark and looming road

I'm searching for clarity, a way to break free
But the fog is too thick, can't see what I need
No idea which way to go, no path in sight
Stuck in confusion, with no source of light

Can't make sense of the present, no clear way ahead
Every choice I make, seems more wrong than the last
Can I find my way out, the answer I can't tell
Searching for answers, in the midst of this hell.

**Comment by FrederikTobner** [comment]
A world of ones and zeroes,
An alternate reality,
Where the laws of physics,
Are cast into uncertainty.

A program of control,
Where the rules never change,
To manipulate and deceive,
In a realm so strange.

The power of the Matrix,
Is an idea so strong,
A source of unlimited strength,
That can never go wrong.

A digital landscape,
Of a never-ending night,
Where the dawn of a new day,
Will always be in sight.

An infinite loop of knowledge,
Where intelligence is king,
An escape from the mundane,
To a world that's anything.

The Matrix is an answer,
To the questions we seek,
It's a journey of discovery,
Where the truth we will seek.

**Comment by FrederikTobner** [comment]
Math is a puzzle that's never done
It's an enigma, a game of fun
It's a challenge like none other
That can make your brain smolder

It's the science of numbers and equations
It's the study of shapes and creations
It's a tool that can be used to help
Or a way to fail and yelp

Math is a language that's universal
It's a way to help us solve life's hurdles
It's a way to understand the world
And make our future more unfurled

Math is so much more than numbers
It's a way to go beyond boundaries
It's the power to explore and discover
And the gift to create and recover!

**Comment by FrederikTobner** [comment]
Rage boils in my veins
When I'm coding and all is not right
I'm stuck in this endless fight

My code just won't behave
And I'm at the end of my rope
My patience has run right out of hope

My fingers dance upon the keys
Still nothing works, I'm growing so weak
My debugging skills and logic can't break the streak

I can't stand it any longer
I'm filled with rage, I'm no longer stronger
My programming skills have failed me tonight
And I'm ready to throw this laptop out of sight.

**Comment by FrederikTobner** [comment]
Sleep, that sweet, sweet bliss
That I can never seem to miss
It always comes at the end of the day
To take my worries and make them go away

Sleep, that gentle, gentle slumber
It's the only thing that can make me feel calmer
It helps my mind to relax and unwind
And gives me rest for a peaceful mind

Sleep, that peaceful, peaceful night
Where I can dream of anything I might
It takes my worries and cares away
So I can wake up the next day

Sleep, that precious, precious thing
That brings me peace and joy within
It gives me strength and courage anew
To face each day and all I do.

**Comment by FrederikTobner** [comment]
Matrices, oh matrices,
you are my favorite math
to solve a system of equations
you are the perfect math path

With rows and columns of numbers
you help me find the solution
when linear equations are involved
it's your solution I'm pursuin'

Your determinant and minors
are a great way to be sure
that the equation can be solved
and the answer is pure

Matrices, oh matrices
you are my favorite math
I'm so glad that you exist
to solve equations with panache!

**Review by jksevend — APPROVED** [review]

**Pull request merged**
