### PR TITLE
docs: New architecture design

### PR DESCRIPTION
**Pull request by jksevend**

### CODE REVIEW

**Review by FrederikTobner — CHANGES_REQUESTED** [review]
I don't think it is a good naming convention to seperate the engine in front-, middle- and lowend. Front layer/Front end layer, middle/intermediate layer and back/backend/lowlevel layer would be more fitting i guess. But overall I like the new architecture and the way it is split in 3 layers.

In the future we may want to specify the architecture of a specific component (like the CLI, Tooling, Physics, Graphics, Core) in a seperate file.

**Comment by jksevend** [comment]
> I don't think it is a good naming convention to seperate the engine in front-, middle- and lowend. Front layer/Front end layer, middle/intermediate layer and back/backend/lowlevel layer would be more fitting i guess. But overall I like the new architecture and the way it is split in 3 layers.

What do you think about `Base Layer`, `Middle Layer` and `Interaction Layer`?

**Comment by FrederikTobner** [comment]
> > I don't think it is a good naming convention to seperate the engine in front-, middle- and lowend. Front layer/Front end layer, middle/intermediate layer and back/backend/lowlevel layer would be more fitting i guess. But overall I like the new architecture and the way it is split in 3 layers.
> 
> What do you think about `Base Layer`, `Middle Layer` and `Interaction Layer`?

Thats better 😊

**Review by FrederikTobner — APPROVED** [review]
lgtm

**Pull request merged**
